#!/bin/bash
# This script bundles the local git repository, gets the size with 'du -sh ' waitsfour seconds and deletes the bundle.
git bundle create tmp.bundle --all
du -sh tmp.bundle
sleep 4
rm tmp.bundle
